language: python
python: 2.7

env:
- TOXENV=py26 LUA=libluajit-5.1-dev
- TOXENV=py27 LUA=libluajit-5.1-dev
- TOXENV=py33 LUA=libluajit-5.1-dev
- TOXENV=py34 LUA=libluajit-5.1-dev
- TOXENV=py26 LUA=lua5.2-dev
- TOXENV=py27 LUA=lua5.2-dev
- TOXENV=py33 LUA=lua5.2-dev
- TOXENV=py34 LUA=lua5.2-dev

install:
- sudo apt-get install $LUA
- pip install -U tox

script: tox
